from http.server import BaseHTTPRequestHandler, HTTPServer
import json

class MockOllama(BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        print("Received request:", post_data)
        
        self.send_response(200)
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        
        # Check if it's a review or a patch request
        try:
            req_json = json.loads(post_data)
            prompt = req_json.get("prompt", "")
        except:
            prompt = ""
            
        if "unified git patch" in prompt:
            # Fix phase response
            fake_patch = """```diff
--- a/scripts/multipass/multipass-launch.sh
+++ b/scripts/multipass/multipass-launch.sh
@@ -10,2 +10,2 @@
-echo "Old"
+echo "Fixed by AI"
```"""
            response = {"response": fake_patch}
        else:
            # Review phase response
            fake_review = {
                "one_line_summary": "Dummy review generated by mock server.",
                "top_issues": [
                    {
                        "id": "1",
                        "title": "Fix the echo statement",
                        "severity": "low",
                        "target_files": ["scripts/multipass/multipass-launch.sh"],
                        "suggested_action": "Update the echo statement."
                    }
                ],
                "categorize": {"features": 1, "refactor": 0, "config": 0, "tests": 0, "infra": 0},
                "llm_review": {"bugs": "None", "regressions": "None", "missing_tests": "None", "architecture": "Looks good.", "performance": "Fast."}
            }
            response = {"response": "```json\n" + json.dumps(fake_review) + "\n```"}
        
        self.wfile.write(json.dumps(response).encode('utf-8'))

if __name__ == '__main__':
    server = HTTPServer(('localhost', 11434), MockOllama)
    print('Starting mock Ollama server on port 11434...')
    server.serve_forever()
