from http.server import BaseHTTPRequestHandler, HTTPServer
import json

class MockOllama(BaseHTTPRequestHandler):
    def _write_json(self, payload, status=200):
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path == "/api/tags":
            self._write_json({"models": [{"name": "mock-model"}]})
            return
        self._write_json({"error": "not found"}, status=404)

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        print("Received request:", post_data)

        try:
            req_json = json.loads(post_data)
            messages = req_json.get("messages", [])
            prompt = messages[-1].get("content", "") if messages else req_json.get("prompt", "")
        except Exception:
            prompt = ""

        if self.path != "/v1/chat/completions":
            self._write_json({"error": "not found"}, status=404)
            return

        if "unified git patch" in prompt:
            fake_patch = """```diff
--- a/scripts/multipass/multipass-launch.sh
+++ b/scripts/multipass/multipass-launch.sh
@@ -10,2 +10,2 @@
-echo "Old"
+echo "Fixed by AI"
```"""
            content = fake_patch
        else:
            fake_review = {
                "one_line_summary": "Dummy review generated by mock server.",
                "top_issues": [
                    {
                        "title": "Fix the echo statement",
                        "severity": "low",
                        "target_files": ["scripts/multipass/multipass-launch.sh"],
                        "anchor": {
                            "file": "scripts/multipass/multipass-launch.sh",
                            "function": "main",
                            "snippet": "echo \"Old\""
                        },
                        "what_is_wrong": "The script prints an outdated placeholder message.",
                        "why_dangerous": "Operators may think the real launch path ran successfully when it did not.",
                        "suggested_action": "Update the echo statement."
                    }
                ],
                "categorize": {"features": 0, "refactor": 0, "config": 0, "tests": 1, "infra": 0},
                "llm_review": {"bugs": "Found one low-risk bug.", "regressions": "No confirmed regression.", "missing_tests": "A shell-level smoke test is missing.", "architecture": "Looks good.", "performance": "No issue.", "security": "No issue."}
            }
            content = "```json\n" + json.dumps(fake_review) + "\n```"

        response = {
            "id": "chatcmpl-mock",
            "object": "chat.completion",
            "created": 0,
            "model": req_json.get("model", "mock-model"),
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": content},
                    "finish_reason": "stop"
                }
            ]
        }
        self._write_json(response)

if __name__ == '__main__':
    server = HTTPServer(('localhost', 11434), MockOllama)
    print('Starting mock Ollama server on port 11434...')
    server.serve_forever()
